version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=insult
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    # depends_on:
      # - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # db:
    # image: postgres:14-alpine
    # ports:
      # - "5432:5432"
    # environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=insult
    # volumes:
      # - /opt/docker/postgres:/var/lib/postgresql/data
    # restart: unless-stopped